[phases.setup]
nixPkgs = ['nodejs', 'npm']  # или python, если backend на Python

[phases.install]
cmds = ['cd frontend && npm install']  # или в backend, если бэкенд

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && npm run start'
